"""initial schema

Revision ID: af8ae9ba8ea1
Revises: 
Create Date: 2026-05-09 16:57:13.746069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'af8ae9ba8ea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('classifier_path', sa.String(length=512), nullable=False),
    sa.Column('regressor_path', sa.String(length=512), nullable=True),
    sa.Column('feature_pipeline_path', sa.String(length=512), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_dataset_size', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_model_versions_version'))
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('auto_approve_threshold', sa.Float(), nullable=False),
    sa.Column('warn_threshold', sa.Float(), nullable=False),
    sa.Column('block_threshold', sa.Float(), nullable=False),
    sa.Column('allow_override', sa.Boolean(), nullable=False),
    sa.Column('specific_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('DEVELOPER', 'DEVOPS', 'TEAM_LEAD', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('oauth_provider', sa.String(length=32), nullable=True),
    sa.Column('oauth_subject', sa.String(length=128), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject', name='uq_users_oauth')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'GITLAB', name='git_provider'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('ci_platform', sa.Enum('GITHUB_ACTIONS', 'BUILDKITE', name='ci_platform'), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('package_manager', sa.String(length=32), nullable=True),
    sa.Column('has_dockerfile', sa.Boolean(), nullable=False),
    sa.Column('webhook_secret_id', sa.String(length=128), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_repositories_policy_id_policies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('provider', 'full_name', name='uq_repositories_provider_full_name')
    )
    op.create_table('commits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('parent_sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=254), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_commits_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commits')),
    sa.UniqueConstraint('repository_id', 'sha', name='uq_commits_repository_sha')
    )
    op.create_index('ix_commits_author_email_committed_at', 'commits', ['author_email', 'committed_at'], unique=False)
    op.create_table('build_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.BigInteger(), nullable=True),
    sa.Column('external_run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'CANCELLED', 'IN_PROGRESS', name='build_status'), nullable=False),
    sa.Column('failure_class', sa.Enum('SUCCESS', 'OOM_KILLED', 'TEST_TIMEOUT', 'DEPENDENCY_ERROR', 'DOCKER_BUILD_FAILED', 'NETWORK_ERROR', name='failure_class'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('peak_memory_mb', sa.Float(), nullable=True),
    sa.Column('image_size_mb', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], name=op.f('fk_build_history_commit_id_commits'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_build_history_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_build_history')),
    sa.UniqueConstraint('repository_id', 'external_run_id', name='uq_build_repo_run')
    )
    op.create_index('ix_build_failure_class', 'build_history', ['failure_class'], unique=False)
    op.create_index('ix_build_repository_completed_at', 'build_history', ['repository_id', 'completed_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('commit_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('predicted_class', sa.Enum('SUCCESS', 'OOM_KILLED', 'TEST_TIMEOUT', 'DEPENDENCY_ERROR', 'DOCKER_BUILD_FAILED', 'NETWORK_ERROR', name='failure_class'), nullable=False),
    sa.Column('class_probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('AUTO_APPROVE', 'WARN', 'BLOCK', name='prediction_decision'), nullable=False),
    sa.Column('predicted_memory_mb', sa.Float(), nullable=True),
    sa.Column('predicted_duration_min', sa.Float(), nullable=True),
    sa.Column('predicted_image_size_mb', sa.Float(), nullable=True),
    sa.Column('feature_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inference_time_ms', sa.Integer(), nullable=False),
    sa.Column('overridden_by_user_id', sa.Integer(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Enum('SUCCESS', 'OOM_KILLED', 'TEST_TIMEOUT', 'DEPENDENCY_ERROR', 'DOCKER_BUILD_FAILED', 'NETWORK_ERROR', name='failure_class'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], name=op.f('fk_predictions_commit_id_commits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_predictions_model_version_id_model_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['overridden_by_user_id'], ['users.id'], name=op.f('fk_predictions_overridden_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_predictions_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index('ix_predictions_commit_id', 'predictions', ['commit_id'], unique=False)
    op.create_index('ix_predictions_decision', 'predictions', ['decision'], unique=False)
    op.create_index('ix_predictions_repo_created_at', 'predictions', ['repository_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_repo_created_at', table_name='predictions')
    op.drop_index('ix_predictions_decision', table_name='predictions')
    op.drop_index('ix_predictions_commit_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_build_repository_completed_at', table_name='build_history')
    op.drop_index('ix_build_failure_class', table_name='build_history')
    op.drop_table('build_history')
    op.drop_index('ix_commits_author_email_committed_at', table_name='commits')
    op.drop_table('commits')
    op.drop_table('repositories')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('policies')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
